config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :polishes

  root "polishes#index"

end

app/models/polish.rb
class Polish < ActiveRecord::Base
  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [
    :sorted_by,
    :search_query,
    :with_color_group,
    :with_polish_type,
    :with_brand_name,
    :with_created_at_gte
    ]
  )
  scope :with_color_group, lambda { |color_groups|
    where(color_group: [*color_groups])
  }

  scope :with_brand_name, lambda { |brand_names|
    where(brand_name: [*brand_names])
  }

  scope :with_polish_type, lambda { |polish_types|
    where(polish_type: [*polish_types])
  }

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/
      # Simple sort on the created_at column.
      # Make sure to include the table name to avoid ambiguous column names.
      # Joining on other tables is quite common in Filterrific, and almost
      # every ActiveRecord table has a 'created_at' column.
      order("polishes.created_at #{ direction }")
    when /^color_name_/
      # Simple sort on the name colums
      order("LOWER(polishes.color_name) #{ direction }, LOWER(polishes.color_name) #{ direction }")
    when /^polish_type/
      # Simple sort on the name colums
      order("LOWER(polishes.polish_type) #{ direction }, LOWER(polishes.polish_type) #{ direction }")
    else
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

  scope :search_query, lambda { |query|
    return nil  if query.blank?

    # condition query, parse into individual keywords
    terms = query.downcase.split(/\s+/)

    # replace "*" with "%" for wildcard searches,
    # append '%', remove duplicate '%'s
    terms = terms.map { |e|
      (e.gsub('*', '%') + '%').gsub(/%+/, '%')
    }
    # configure number of OR conditions for provision
    # of interpolation arguments. Adjust this if you
    # change the number of OR conditions.
    num_or_conds = 2
    where(
      terms.map { |term|
        "(LOWER(polishes.color_name) LIKE ? OR LOWER(polishes.brand_name) LIKE ?)"
      }.join(' AND '),
      *terms.map { |e| [e] * num_or_conds }.flatten
    )
  }

  def self.options_for_sorted_by
    [
      ['Color Name (a-z)', 'color_name_asc'],
      ['Creation Date (newest first)', 'created_at_desc'],
      ['Creation Date (oldest first)', 'created_at_asc'],
      ['Polish Type (a-z)', 'polish_type_asc']
    ]
  end

  def height_finder(polish)
    case polish.brand_name
    when 'butter London'
      return "65x65"
    when 'Essie'
      return "65x140"
    when 'OPI'
    end
  end

  validates :brand_name,
    presence: true,
    format: {
      with: /\A[a-zA-Z ']+\z/
    },
    inclusion: {
      in: ['butter London', 'Essie', 'OPI']
    }
  validates :color_name,
    presence: true
  validates :brand_number,
    presence: true,
    numericality: {
      greater_than_or_equal_to: 0,
      only_integer: true
    }
  validates :upc,
    presence: true,
    format: {
      :multiline => true,
      with: /^[0-9]{1,45}$/
    }
  validates :color_group,
    presence: true,
    format: {
      with: /\A[a-zA-Z ']+\z/
    },
    inclusion: {
      in: ['Pinks', 'Neutrals', 'Grays', 'Corals', 'Reds', 'Plums', 'Deeps', 'Blues', 'Greens']
    }
  validates :polish_type,
    presence: true,
    format: {
      with: /\A[a-zA-Z ']+\z/
    },
    inclusion: {
      in: ['Metallics', 'Mattes', 'Effects', 'None']
    }
  validates :hex_color,
    presence: true
  validates :description,
    presence: true
  validates :image_url,
    presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polishes_controller.rb
class PolishesController < ApplicationController
  def new
    @polish = Polish.new
    @polish_types = ['Metallics', 'Mattes', 'Effects', 'None']
    @brands = ['Essie', 'butter London', 'OPI']
    @color_groups = ['Pinks', 'Neutrals', 'Grays', 'Corals', 'Reds', 'Plums', 'Deeps', 'Blues', 'Greens']
  end

  def index
    @button_strings = ['FTW!', 'are the best', 'are for winners', 'are for beautiful people', ': best thing since sliced bread?', 'brighten up any look', 'are so hot right now', 'look fabulous with your skin tone', 'are perfect for this season', 'are a winning choice', 'command respect', 'work with any nail shape', 'increase productivity', 'are a festive choice', 'enhance any style']
    @polish_types = ['Metallics', 'Mattes', 'Effects', 'None']
    @brands = ['Essie', 'butter London', 'OPI']
    @color_groups = ['Pinks', 'Neutrals', 'Grays', 'Corals', 'Reds', 'Plums', 'Deeps', 'Blues', 'Greens']

    @filterrific = initialize_filterrific(
      Polish,
      params[:filterrific],
      select_options: {
        sorted_by: Polish.options_for_sorted_by,
        with_color_group: @color_groups,
        with_polish_type: @polish_types,
        with_brand_name: @brands
      },
    ) or return
    @polishes = @filterrific.find.page(params[:page])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @polish = Polish.find(params[:id])
  end

  def edit
    @polish = Polish.find(params[:id])
    @polish_types = ['Metallics', 'Mattes', 'Effects', 'None']
    @brands = ['Essie', 'butter London', 'OPI']
    @color_groups = ['Pinks', 'Neutrals', 'Grays', 'Corals', 'Reds', 'Plums', 'Deeps', 'Blues', 'Greens']
  end

  def update
    @polish = Polish.find(params[:id])
    if @polish.update(polish_params)
      flash[:notice] = "Successfully updated nail polish"
      redirect_to polishes_path
    else
      Rails.logger.info(@polish.errors.inspect)
      render :edit
    end
  end

  def create
    @polish = Polish.new(polish_params)
    @polish_types = ['Metallics', 'Mattes', 'Effects', 'None']
    @brands = ['Essie', 'butter London', 'OPI']
    @color_groups = ['Pinks', 'Neutrals', 'Grays', 'Corals', 'Reds', 'Plums', 'Deeps', 'Blues', 'Greens']
    if @polish.save
      redirect_to :action => :index
    else
      Rails.logger.info(@polish.errors.inspect)
      render 'new'
    end
  end

  def destroy
    Polish.find(params[:id]).destroy
    redirect_to polishes_path
  end

  private

  def polish_params
    params.require(:polish).permit(
    :brand_name,
    :color_name,
    :brand_number,
    :upc,
    :color_group,
    :polish_type,
    :hex_color,
    :description,
    :image_url)
  end
end

app/helpers/_web_scraper.rb
# require 'HTTParty'
# require 'Nokogiri'
# require 'JSON'
# require 'pry'
#
# def scrape_site(site_url)
#   page = HTTParty.get(site_url)
#   binding.pry
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polish_helper.rb
module PolishHelper

  
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom" style="background: #F7F7F9">
  <div class="container">
      Kamille's Ratchet Nail Salon |
      November 2016 |
      <a href="https://github.com/Kamilleski/ratchet-nail-salon">💾 Source Code</a> |
      <a href="https://www.linkedin.com/in/kamilledelgardo">♀ About Kamille</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-light navbar-fixed-top bg-faded">
  <a class="navbar-brand" href="/">
    <img src="http://emojipedia-us.s3.amazonaws.com/cache/89/ed/89ed3edad37df4e7fac0304b90f2d0c5.png" width="30" height="30" class="d-inline-block align-top" alt="Site Icon">
    Kamille's Ratchet Nail Salon
  </a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <a class="nav-link" href="/polishes/new">Add Polish<span class="sr-only">(current)</span></a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/polishes">All Colors</a>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kamille's Ratchet Nail Salon</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'http://emojipedia-us.s3.amazonaws.com/cache/89/ed/89ed3edad37df4e7fac0304b90f2d0c5.png' %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/css/bootstrap.min.css" integrity="sha384-AysaV+vQoT3kOAXZkl02PThvDr8HYKPZhNT5h/CXfBThSRXQ6jW5DO2ekP5ViFdi" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

  <%= render 'layouts/header' %>
  
  <div class="container container-fluid">

    <%= yield %>

  </div>

  <%= render 'layouts/footer' %>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js" integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.3.7/js/tether.min.js" integrity="sha384-XTs3FgkjiBgo8qjEjBk0tGmf3wPrWtA6coPfQDfFEY8AnYJwjalXCiosYRBIBZX8" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.5/js/bootstrap.min.js" integrity="sha384-BLiI7JTZm+JWlgKa0M0kGRpJbF2J8q+qreVrKBC47e3K6BW78kGLrCkeRX6I9RoK" crossorigin="anonymous"></script>
</body>
</html>

app/views/polishes/_list.html.erb
<div id="filterrific_results">

  <div>
    <%= page_entries_info polishes %>
  </div>

  <div class="card-colums">
    <div class="row">
      <% polishes.each do |p| %>
        <div class="col-xs-12 col-sm-6 col-md-4 col-xlg-3">
          <div class="card text-xs-center">
            <br />
            <% case p.brand_name %>
            <% when 'butter London' %>
              <%= image_tag(p.image_url, size: '140x140', alt: "butter London #{p.color_name}", class: "card-img-top img-responsive center-block") %>
            <% when 'Essie' %>
              <%= image_tag("#{p.image_url}", size: '65x140', alt: "Essie #{p.color_name}", class: "card-img-top img-responsive center-block") %>
            <% when 'OPI' %>
              <%= image_tag("#{p.image_url}", size: '57x140', alt: "OPI #{p.color_name}", class: "card-img-top img-responsive center-block") %>
            <% end %>
            <div class="card-block">
              <h4 class="card-title"><%= "#{p.brand_name} #{p.color_name}" %></h4>
              <p class="card-text"><%= "#{p.description}" %></p>
              <a href="<%= polish_path(id: p.id) %>" class="btn btn-primary" style="background-color: <%= p.hex_color %>"><%= "#{p.color_group} #{@button_strings.sample}" %></a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

<%= will_paginate polishes %>

app/views/polishes/_table_index.html.erb
<table>
  <tr>
    <th>Image</th>
    <th>Brand</th>
    <th>Color Name</th>
    <th>Brand Number</th>
    <th>Color Group</th>
    <th>Type</th>
    <th>UPC</th>
    <th>Hex Color</th>
    <th>Throw Out</th>
    <th>Fix Details</th>
  </tr>
  <% @polishes.each do |p| %>
    <tr>
      <td>
        <% case p.brand_name %>
        <% when 'butter London' %>
          <%= image_tag(p.image_url, size: '140x140', alt: "butter London #{p.color_name}") %>
        <% when 'Essie' %>
          <%= image_tag("#{p.image_url}", size: '65x140', alt: "Essie #{p.color_name}") %>
        <% when 'OPI' %>
          <%= image_tag("#{p.image_url}", size: '57x140', alt: "OPI #{p.color_name}") %>
        <% end %>
      </td>
      <td><%= p.brand_name %></td>
      <td><%= p.color_name %></td>
      <td><%= p.brand_number %></td>
      <td><%= p.color_group %></td>
      <td><%= p.polish_type %></td>
      <td><%= p.upc %></td>
      <td bgcolor="<%= p.hex_color %>"><font color="white"><%= p.hex_color %></font></td>
      <td><%= button_to "Safe Disposal", polish_path(id: p.id), method: :delete, type: "button" %></td>
      <td><%= link_to "Touch up with Acetone", edit_polish_path(id: p.id) %></td>
    </tr>
  <% end %>
</table>

app/views/polishes/edit.html.erb
<h1>Update <%= "#{@polish.brand_name} #{@polish.color_name}" %></h1>
<h3>All Fields Required</h3>
<hr />
<%= form_for @polish, action: 'update' do |f| %>
  <div>
    <%= f.label :brand_name, 'Brand Name' %>
    <%= f.select :brand_name, @brands, autofocus: true %>
  </div>
  <div>
    <%= f.label :color_name, 'Color Name' %>
    <%= f.text_field :color_name, autofocus: true, placeholder: "For the Twill of it" %>
  </div>
  <div>
    <%= f.label :brand_number, 'Brand Number' %>
    <%= f.number_field :brand_number, autofocus: true, placeholder: "702" %>
  </div>
  <div>
    <%= f.label :upc, 'Universal Product Code' %>
    <%= f.number_field :upc, autofocus: true, placeholder: "095008011059" %>
  </div>
  <div>
    <%= f.label :color_group, 'Color Group' %>
    <%= f.select :color_group, @color_groups, autofocus: true, placeholder: "Plums" %>
  </div>
  <div>
    <%= f.label :polish_type, 'Type' %>
    <%= f.select :polish_type, @polish_types, autofocus: true, placeholder: "Metallics" %>
  </div>
  <div>
    <%= f.label :hex_color, 'Hex Color Code' %>
    <%= f.text_field :hex_color, autofocus: true, placeholder: "#5C565F" %>
  </div>
  <div>
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description, autofocus: true, placeholder: "[insert pablum copywriting here]" %>
  </div>
  <div>
    <%= f.label :image_url, 'Image URL' %>
    <%= f.text_field :image_url, autofocus: true, placeholder: "http://www.image.jpg" %>
  </div>
  <div>
    <%= f.submit 'Update Polish' %>
  </div>
<% end %>

app/views/polishes/index.html.erb
<%#
  Filterrific adds the `form_for_filterrific` view helper:
  * adds dom id 'filterrific_filter'
  * applies javascript behaviors:
      * AJAX form submission on change
      * AJAX spinner while AJAX request is being processed
  * sets form_for options like :url, :method and input name prefix
%>
<div class="jumbotron">
  <div class="container">
    <h1>Kamille's Big Bag of Chemicals</h1>
    <p>Check out my collection.</p>
    <p>Click on any card for more information about that polish.</p>
    <p>Filter and sort by the parameters below.</p>
    <hr />
    <div class="row">
      <%= form_for_filterrific @filterrific, class: "form-inline" do |f| %>
        <div class="col-xs-12 col-md-2 col-centered">
          <div class="form-group">
            <label>Search</label>
            <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
            <%= f.text_field(:search_query, class: 'form-control filterrific-periodically-observed') %>
          </div>
        </div>
        <div class="col-xs-12 col-md-2 col-centered">
          <div class="form-group">
            Brand
            <%= f.select(:with_brand_name, @filterrific.select_options[:with_brand_name], { include_blank: '- Any -' }, class: 'form-control', width: "200px") %>
          </div>
        </div>
        <div class="col-xs-12 col-md-2 col-centered">
          <div class="form-group">
            Color Group
            <%= f.select(:with_color_group, @filterrific.select_options[:with_color_group],{ include_blank: '- Any -' }, class: 'form-control') %>
          </div>
        </div>
        <div class="col-xs-12 col-md-2 col-centered">
          <div class="form-group">
            Polish Type
            <%= f.select(:with_polish_type, @filterrific.select_options[:with_polish_type], { include_blank: '- Any -' }, class: 'form-control') %>
          </div>
        </div>
        <div class="col-xs-12 col-md-2 col-centered">
          <div class="form-group">
            Sorted by
            <%= f.select(:sorted_by, @filterrific.select_options[:sorted_by]) %>
          </div>
        </div>
        <div class="col-xs-12 col-md-2 col-centered">
          <div class="form-group">
            <%= link_to(
              'Reset filters',
              reset_filterrific_url,
            ) %>
          </div>
        </div>
          <%# add an automated spinner to your form when the list is refreshed %>
        <%= render_filterrific_spinner %>
      <% end %>
    </div>
  </div>

</div>


<%= render 'polishes/list', polishes: @polishes %>

app/views/polishes/index.js.erb
<% js = escape_javascript(
  render(partial: 'polishes/list', locals: { polishes: @polishes })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/polishes/new.html.erb
<h1>Add a New Polish</h1>
<h3>All Fields Required</h3>
<hr />
<%= form_for @polish, action: 'create' do |f| %>
  <div>
    <%= f.label :brand_name, 'Brand Name' %>
    <%= f.select :brand_name, @brands, autofocus: true %>
  </div>
  <div>
    <%= f.label :color_name, 'Color Name' %>
    <%= f.text_field :color_name, autofocus: true, placeholder: "For the Twill of it" %>
  </div>
  <div>
    <%= f.label :brand_number, 'Brand Number' %>
    <%= f.number_field :brand_number, autofocus: true, placeholder: "702" %>
  </div>
  <div>
    <%= f.label :upc, 'Universal Product Code' %>
    <%= f.number_field :upc, autofocus: true, placeholder: "095008011059" %>
  </div>
  <div>
    <%= f.label :color_group, 'Color Group' %>
    <%= f.select :color_group, @color_groups, autofocus: true, placeholder: "Plums" %>
  </div>
  <div>
    <%= f.label :polish_type, 'Type' %>
    <%= f.select :polish_type, @polish_types, autofocus: true, placeholder: "Metallics" %>
  </div>
  <div>
    <%= f.label :hex_color, 'Hex Color Code' %>
    <%= f.text_field :hex_color, autofocus: true, placeholder: "#5C565F" %>
  </div>
  <div>
    <%= f.label :description, 'Description' %>
    <%= f.text_area :description, autofocus: true, placeholder: "[insert pablum copywriting here]" %>
  </div>
  <div>
    <%= f.label :image_url, 'Image URL' %>
    <%= f.text_field :image_url, autofocus: true, placeholder: "http://www.image.jpg" %>
  </div>
  <div>
    <%= f.submit 'Add New Polish' %>
  </div>
<% end %>

app/views/polishes/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 center-block">
      <div class="panel panel-default polish-show">
        <div class="panel-body">
          <div class="row">
            <div class="col-xs-6">
              <% case @polish.brand_name %>
              <% when 'butter London' %>
                <%= image_tag(@polish.image_url, size: '280x280', alt: "butter London #{@polish.color_name}", class: "img-responsive center-block figure-img img-fluid rounded") %>
              <% when 'Essie' %>
                <%= image_tag("#{@polish.image_url}", size: '130x280', alt: "Essie #{@polish.color_name}", class: "img-responsive center-block figure-img img-fluid rounded") %>
              <% when 'OPI' %>
                <%= image_tag("#{@polish.image_url}", size: '115x280', alt: "OPI #{@polish.color_name}", class: "img-responsive center-block figure-img img-fluid rounded") %>
              <% end %>
              <figcaption class="figure-caption text-xs-center"><%= "#{@polish.brand_name} #{@polish.color_name}" %></figcaption>
            </div>
            <br />
            <div class="col-xs-6">
              <dl>
                <div class="container">
                  <dt class="col-sm-3">Brand Name</dt>
                  <dd class="col-sm-9"><%= @polish.brand_name %></dd>
                </div>
                <div class="container">
                  <dt class="col-sm-3">Color</dt>
                  <dd class="col-sm-9"><%= @polish.color_name %></dd>
                </div>
                <div class="container">
                  <dt class="col-sm-3">Description</dt>
                  <dd class="col-sm-9"><%= @polish.description %></dd>
                </div>
                <div class="container">
                  <dt class="col-sm-3">Color Group</dt>
                  <dd class="col-sm-9"><%= @polish.color_group %></dd>
                </div>
                <div class="container">
                  <dt class="col-sm-3">UPC</dt>
                  <dd class="col-sm-9"><%= @polish.upc %></dd>
                </div>
              </dl>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>